### PR TITLE
Add tree width options

### LINKED ISSUE #772: Is there a way to make playlist list smaller?
So, here is what it looks like right now:

As you can see the left part takes too much space. Is it configurable?  
If it's not then it would be a very nice addition.

### LINKED ISSUE #990: How to change treeview width
---
I don't find the option to change treeview width anywhere? How can i change treeview width (the list that is always show on the left)

1) `uname -a`:
```
5.7.10-arch1-1 #1 SMP PREEMPT x86_64 GNU/Linux
```

2) `cmus --version`:
```
cmus v2.8.0
```

### PR DESCRIPTION
**Pull request by pgaskin**
closes #990
closes #772

### CODE REVIEW

**Comment by pgaskin** [comment]
A few notes:
- I'm not completely familiar with the UI code, so I'm not 100% sure this doesn't cause issues elsewhere, but it seems to work fine right now.
- Since I'm using an int between 1 and 100, we lose precision (it used to divide by 3), but this is mostly irrelevant since terminal windows aren't wide enough to make this have a significant effect. If this is an issue, I could parse it as a double or a fraction with a numerator/denominator instead.

**Review by pgaskin — COMMENTED** [review]
Tested tree/library/playlist views, mouse events, resizing window, setting window size from rc/autosave/command-line/remote.

**Comment by nefthy** [comment]
> * I'm not completely familiar with the UI code, so I'm not 100% sure this doesn't cause issues elsewhere, but it seems to work fine right now.
IMO its better to handle the width in columns since that is the basic underlying unit.

**Comment by pgaskin** [comment]
What do you think of renaming it to `tree_width` and making it accept either a fixed value (later constrained to the max width of the window) or a percentage (if there's a percent sign at the end).

**Comment by nefthy** [comment]
sounds good

**Comment by pgaskin** [comment]
Actually, I think I have a better idea: adding an optional `tree_width_max` option to limit the maximum width, and increasing the maximum `tree_width_percent` to 100%. This will allow both: setting a fixed size and still making it work properly at smaller window sizes, limiting the size only on large window sizes, and keeping the old behaviour.

**Comment by nefthy** [comment]
Also a good option.

**Review by pgaskin — COMMENTED** [review]
Tested tree/library/playlist views, mouse events, resizing window, setting window size from rc/autosave/command-line/remote with:
- `tree_width_percent=100` `tree_width_max=60`
- `tree_width_percent=33` `tree_width_max=60`
- `tree_width_percent=33` `tree_width_max=0`
- `tree_width_percent=1` `tree_width_max=9999`

**Comment by pgaskin** [comment]
@nefthy, this is ready for review now.

**Comment by pgaskin** [comment]
I took a closer look at the code, and I'm now fairly certain this won't cause issues elsewhere.

**Review by nefthy — CHANGES_REQUESTED** [review]
Looks good, but please rebase, as there is a conflict with another merge

**Review by nefthy — APPROVED** [review]

**Comment by nefthy** [comment]
thanks

**Pull request merged**
