### PR TITLE
Show recognized names in message for bad option value

### PR DESCRIPTION
**Pull request by gavtroy**

### CODE REVIEW

**Review by pgaskin — APPROVED** [review]
Tested, code looks good, is useful.

**Comment by pgaskin** [comment]
@flyingmutant

**Comment by pgaskin** [comment]
@flyingmutant

**Comment by flyingmutant** [comment]
> @flyingmutant

One ping is enough.

**Comment by pgaskin** [comment]
> One ping is enough

Okay, just thought you might have missed it since I did it at the same time as some other PRs you merged.

**Comment by flyingmutant** [comment]
> Okay, just thought you might have missed it since I did it at the same time as some other PRs you merged.

I think assigning PR's you think are ready can be handy -- that way, it will be easy to see all of them at a glance.

**Pull request merged**
