### PR TITLE
Avoid -I$(pwd)

### PR DESCRIPTION
**Pull request by tomty89**
It for example causes our uchar.h to conflict with system uchar.h in Android.

I fixed the ffmpeg "build trial" with `-I$topdir/ip`, but shall we just ditch the trial? I honestly don't see the sense in "try building something that we are going to build"...

### CODE REVIEW

**Comment by tomty89** [comment]
```
checking for successful build of ffmpeg.c... .tmp-23-prog.c:32:10: fatal error: 'libswresample/swresample.h' file not found
#include <libswresample/swresample.h>
         ^
1 error generated.
no
```

Not my problem I suppose. :-)

**Comment by nefthy** [comment]
So on android the compiler prefers the system uchar.h over our uchar.h?

**Comment by tomty89** [comment]
More like if you use `-I`, you make the cmus uchar.h override the android uchar.h so they cannot co-exist.

**Comment by tomty89** [comment]
`stdatomic.h` in Android includes `uchar.h` for `char16_t` and `char32_t`. If we include our uchar.h by making `$(pwd)` a search path, the types would become unknown as we are overriding the system uchar.h with ours. And I don't think `-I$(pwd)` is an appropriate approach anyway.

**Comment by nefthy** [comment]
could you please post the compiler output?

**Comment by tomty89** [comment]
```
$ cd cmus-build/
$ git diff
diff --git a/scripts/checks.sh b/scripts/checks.sh
index 41c9f3e..ab52b33 100644
--- a/scripts/checks.sh
+++ b/scripts/checks.sh
@@ -451,7 +451,7 @@ try_compile_link()
                echo "$1" > $__src || exit 1
                shift
                __cmd="$CC $__src -o $__exe $CFLAGS $LDFLAGS $@"
-               $CC $__src -o $__exe $CFLAGS $LDFLAGS "$@" 2>/dev/null
+               $CC $__src -o $__exe $CFLAGS $LDFLAGS "$@"
                ;;
        cxx)
                __src=`tmp_file prog.cc`
$ ./configure
checking for program gcc... /data/data/com.termux/files/usr/bin/gcc
checking for program gcc... /data/data/com.termux/files/usr/bin/gcc
checking for C11 (with atomics support)... In file included from .tmp-0-prog.c:2:
In file included from /data/data/com.termux/files/usr/lib/clang/7.0.1/include/stdatomic.h:31:
/data/data/com.termux/files/usr/include/stdatomic.h:269:19: error:
      unknown type name 'char16_t'
  typedef _Atomic(char16_t)             atomic_char16_t;
                  ^
/data/data/com.termux/files/usr/include/stdatomic.h:270:19: error:
      unknown type name 'char32_t'
  typedef _Atomic(char32_t)             atomic_char32_t;
                  ^
2 errors generated.
In file included from .tmp-1-prog.c:2:
In file included from /data/data/com.termux/files/usr/lib/clang/7.0.1/include/stdatomic.h:31:
/data/data/com.termux/files/usr/include/stdatomic.h:269:19: error:
      unknown type name 'char16_t'
  typedef _Atomic(char16_t)             atomic_char16_t;
                  ^
/data/data/com.termux/files/usr/include/stdatomic.h:270:19: error:
      unknown type name 'char32_t'
  typedef _Atomic(char32_t)             atomic_char32_t;
                  ^
2 errors generated.
In file included from .tmp-2-prog.c:2:
In file included from /data/data/com.termux/files/usr/lib/clang/7.0.1/include/stdatomic.h:31:
/data/data/com.termux/files/usr/include/stdatomic.h:269:19: error:
      unknown type name 'char16_t'
  typedef _Atomic(char16_t)             atomic_char16_t;
                  ^
/data/data/com.termux/files/usr/include/stdatomic.h:270:19: error:
      unknown type name 'char32_t'
  typedef _Atomic(char32_t)             atomic_char32_t;
                  ^
2 errors generated.
no
configure failed.
$
```

**Comment by tomty89** [comment]
This apparently works as well:
```
diff --git a/uchar.h b/uchar.h
index 4be1338..a9fade8 100644
--- a/uchar.h
+++ b/uchar.h
@@ -21,6 +21,10 @@

 #include <stddef.h> /* size_t */

+#if defined (__ANDROID__)
+#include_next "uchar.h"
+#endif
+
 typedef unsigned int uchar;

 extern const char hex_tab[16];
```
But `-I$(pwd)` makes little sense to me anyway.

**Comment by nefthy** [comment]
thanks

**Pull request merged**
