### PR TITLE
Add mouse bindings for right third of status bar

### PR DESCRIPTION
**Pull request by pgaskin**
Default to play/volume.

### CODE REVIEW

**Review by pgaskin — COMMENTED** [review]
Tested. Works as expected.

https://copr.fedorainfracloud.org/coprs/pgaskin/cmus-testing/build/6176496/
https://github.com/pgaskin/cmus/commits/001f1a4806e48c9f298e41d047e43d669c9475c8
https://nightly.link/pgaskin/rpms/actions/runs/5568630004

**Comment by pgaskin** [comment]
Thoughts, @flyingmutant?

**Comment by flyingmutant** [comment]
Thanks, will review later this week.

**Review by gavtroy — APPROVED** [review]
Looks good with the minor caveat that documentation doesn't mention that "_right" means "the rightmost third of the bar", and I'm not sure why we pick 33% rather than 50%. But no big deal.

To make it more intuitive, it might be nice to change the default `format_statusline` to move the volume indication to the right of the bar (and maybe add the missing % symbol). For instance it could look like -
image
But the PR does do what it says on the tin.

**Comment by pgaskin** [comment]
I chose 33% since with 50%, I changed the volume by accident too frequently (especially since my mouse usually starts over the track list).

Changing the default position of the volume indicator would probably be a good idea for another PR.

**Pull request merged**
