### PR TITLE
Fixes channel map for multichannel flac files

### LINKED ISSUE #1070: FLAC with more than 5 channels broken
It is not clear to me whether cmus supports high-resolution flac files.

### PR DESCRIPTION
**Pull request by nefthy**
Fixes #1070

### CODE REVIEW

**Review by pgaskin — APPROVED** [review]
LGTM

**Comment by pgaskin** [comment]
@nefthy, can you rebase this on master?

**Comment by nefthy** [comment]
sure here you go

**Comment by pgaskin** [comment]
@flyingmutant?

**Comment by flyingmutant** [comment]
Thanks!

**Pull request merged**
