### PR TITLE
some s/when/if/

### PR DESCRIPTION
**Pull request by avoidr**

### CODE REVIEW

**Comment by flyingmutant** [comment]
Thanks for the PR!

Are you a native speaker? Some of the "when" uses you've changed look OK to me — but English is foreign language for me.

**Comment by avoidr** [comment]
I am not native, but I'm pretty sure that it's now correct. I didn't change anything I wasn't sure of. Some examples are more clear than others.

What's PR here? Either way, you're welcome, I guess :P

>Some of the "when" uses you've changed look OK to me

Do you mean that the new version looks now correct, or do you think that I may have changed something which was correct before?

**Comment by flyingmutant** [comment]
PR means Pull Request :-)

**Comment by avoidr** [comment]
Ah, right. I kept thinking "Public Relations", lol. At least the first two letters in each word were correct :-D

**Pull request merged**
