### PR TITLE
Check only title in track title replacement

### PR DESCRIPTION
**Pull request by mrHeavenli**
We only need to check if title is null to replace it with the filename in the track info.

### CODE REVIEW

**Comment by mrHeavenli** [comment]
@flyingmutant 
I see Mr. Gaskin is very busy, can you review this?

**Comment by flyingmutant** [comment]
Can you please explain why is this change required?

**Comment by gavtroy** [comment]
Normally if a track doesn't have tags then `altformat_*` are used, which by default either show the full path (`%f`) or the basename (`%F`) depending on context. This breaks with your change, and I'm not sure what it attempts to fix in return. If you just want the track window formatting to align you just need to match `altformat_trackwin` to `format_trackwin` and match `altformat_playlist` to `format_playlist`, except replacing `%t` with `%F`.

**Comment by mrHeavenli** [comment]
> Can you please explain why is this change required?

Sure. When I was doing something with playerctl, tracks that had no title tag just gave nothing. So I looked at the code and found that the title would be filled in with the filename if there was no title tag, but that didn't show in the metadata that playerctl gave me. So I deleted that bit in the PR, and it actually gave me the filename in the metadata. I didn't really understand what the condition was there for, but now @gavtroy is telling me that it breaks something when removed. I guess this could also be done in mpris.c without breaking something?
by adding something in this region:
```c
if (ti->title) {
			char corrected[u_str_print_size(ti->title)];
			u_to_utf8(corrected, ti->title);
			CK(mpris_msg_append_ss_dict(reply,
					"xesam:title", corrected));
		}

```

**Comment by mrHeavenli** [comment]
@gavtroy What do you think of this?

mpris.c
```c
#include "path.h"
...
if (ti->title) {
	char corrected[u_str_print_size(ti->title)];
	u_to_utf8(corrected, ti->title);
	CK(mpris_msg_append_ss_dict(reply,
			"xesam:title", corrected));
}else{
	char corrected[u_str_print_size(path_basename(ti->filename))];
	u_to_utf8(corrected, path_basename(ti->filename));
	CK(mpris_msg_append_ss_dict(reply,
			"xesam:title", corrected));
}
```

**Comment by gavtroy** [comment]
With spaces around the else tidied up, looks good to me.

**Comment by mrHeavenli** [comment]
@flyingmutant now gavtroy approves, can this be put in?

**Pull request merged**
