### PR TITLE
Implement mouse events for status bar

### LINKED ISSUE #1012: Feature request: Allow binding mouse events to the status bar
`cmus --version`:

```
cmus v2.8.0
```

This would allow seeking and playing/pausing with the mouse by binding it to mouse events over the status bar, which are currently unused.

### PR DESCRIPTION
**Pull request by pgaskin**
closes #1012

### CODE REVIEW

**Review by pgaskin — COMMENTED** [review]
Tested:
- Ensured old mouse events in other areas still work correctly.
- Tested new default bindings for mouse events on the status bar.
- Tested right click event for status bar.
- Tested the above on multiple views.

**Comment by pgaskin** [comment]
This is ready for review. If you don't want default bindings for the new events, I can revert them.

Note: I recommend viewing these changes [ignoring whitespace](https://github.com/cmus/cmus/pull/1013/files?diff=unified&w=1), since the diff is a lot more readable that way.

**Review by nefthy — CHANGES_REQUESTED** [review]
There are conflicts in keys.c please rebase and resolve this.

**Review by pgaskin — COMMENTED** [review]
Tested:
- Ensured mouse events work correctly on the status bar after the merge.
- Ensured fix from #1011 still works after the merge.

**Review by nefthy — APPROVED** [review]

**Comment by pgaskin** [comment]
@flyingmutant

**Comment by flyingmutant** [comment]
Merged, thanks!

**Pull request merged**
