### PR TITLE
ip/mp4: add metadata support for bpm/tempo

### PR DESCRIPTION
**Pull request by lennonhill**
Implements #877

### CODE REVIEW

**Comment by nefthy** [comment]
@lennonhill  Do you have a test file or two?

**Comment by lennonhill** [comment]
I generated some examples using both ffmpeg and mp4tags from libmp4v2. They are all displayed correctly in cmus.
[ip_mp4_bpm_tests.zip](https://github.com/cmus/cmus/files/2919573/ip_mp4_bpm_tests.zip)

**Comment by nefthy** [comment]
@flyingmutant patch looks good. Test files work fine.

**Comment by flyingmutant** [comment]
Hmm, what guarantees that `buf` is `\0`-terminated?

**Comment by lennonhill** [comment]
snprintf does, which writes at most 6 bytes to buf, including the null byte.

**Comment by flyingmutant** [comment]
True, looks like I had a brain seizure :-) Thanks, merged!

**Pull request merged**
