### PR TITLE
Fix configure function checks for recent clang versions

### PR DESCRIPTION
**Pull request by pgaskin**
Simply try taking the address of the function instead of doing funny stuff with the pointer.

### CODE REVIEW

**Review by pgaskin — COMMENTED** [review]
Tested on multiple compiler versions with and without strict and/or pedantic C89+, with existent and non-existent functions.

**Comment by pgaskin** [comment]
Also see termux/termux-packages#15852.

**Comment by pgaskin** [comment]
@flyingmutant

**Review by gavtroy — APPROVED** [review]
Looks okay. It might also have been enough to `void *x = (void*) &$1;` rather than using a function pointer signature.

**Comment by pgaskin** [comment]
That results in a warning in some configurations (and an error if the compiler is configured to be strict) @gavtroy.

**Comment by flyingmutant** [comment]
Thanks! Merged.

**Pull request merged**
