### PR TITLE
Implement mouse events for title bar

### LINKED ISSUE #1015: Feature request: Allow binding mouse events to the title bar
`cmus --version`:

```
cmus v2.8.0
```

Like #1012, but for the title bar.

### PR DESCRIPTION
**Pull request by pgaskin**
closes #1015

### CODE REVIEW

**Comment by pgaskin** [comment]
@nefthy

**Review by nefthy — CHANGES_REQUESTED** [review]
Works nicely. I'd favor writing out title at least for the user facing part, if you don't mind.

**Comment by pgaskin** [comment]
Ok, I'll change that later today. I'll probably submit another PR to add the new mouse events to the docs since they don't all have default bindings.

Also, do you and @flyingmutant think I should bind scroll events to switching views by default?

**Comment by nefthy** [comment]
scroll on title bar to switch views seems sensible. Do you have a default for the status bar? If not, seek +/-5 seems sensible.

**Comment by pgaskin** [comment]
Yep, I already included the status bar defaults in #1013.

**Review by pgaskin — COMMENTED** [review]
Tested.

**Comment by pgaskin** [comment]
@nefthy

**Review by nefthy — APPROVED** [review]
LGTM

**Comment by flyingmutant** [comment]
Thanks!

**Pull request merged**
