### PR TITLE
Add multiple playlists feature

### PR DESCRIPTION
**Pull request by mahkoh**

### CODE REVIEW

**Comment by losingkeys** [comment]
Hmm, If I:

    make clean && ./configure prefix=. DEBUG=2 CONFIG_ROAR=n CONFIG_ALSA=y && make && make install
At 0c687d152e1bf5f7e61c82f7297865817e5fe4cb, I still can't get it to restore the selected playlist on startup. Am I building it wrong?

**Comment by mahkoh** [comment]
You have to enable the resume option.

**Comment by losingkeys** [comment]
Ohh I wasn't talking about the last played _track_, but where the `*` marker is. Is that also tied to the resume option? It seems like they're similar, but different enough that this could just be the default (restoring where the `*`), and the resume option could work across playlists/the file browser/the library/etc.

**Comment by mahkoh** [comment]
There is no mechanism in cmus to store such state except for the resume feature.

**Comment by mahkoh** [comment]
There are still some problems that need to be fixed:

- When activating a playlist and follow is enabled, the cursor moves into the track window. This should not happen.

- When adding tracks from the browser window the cursor does not move.

**Comment by flyingmutant** [comment]
And I am still to review the whole thing — only got around 50% so far.

**Comment by mahkoh** [comment]
Rebased on top of master.

**Comment by flyingmutant** [comment]
Even if there are some unsolved issues (https://github.com/cmus/cmus/pull/485#issuecomment-236263927), this is a *fantastic* PR.

Thanks a lot for your hard work (and especially for splitting everything in nice self-contained commits) — and sorry it took me so long to review and merge.

Fixes #108.

**Comment by ayancey** [comment]
Is there any documentation on this feature? I could not find any.

**Comment by Yodzeity** [comment]
I'm sorry, is this abandoned?

**Comment by criztovyl** [comment]
@Yodzeity Not exactly, [it's merged](https://github.com/cmus/cmus/pull/485#event-758921691) :)

**Pull request merged**
