### PR TITLE
Remove AV_CODEC_{CAP,FLAG}_TRUNCATED for FFmpeg 6 compatibility

### LINKED ISSUE #1251: FFmpeg 6.0 compatibility fix
FreeBSD ffmpeg [port](https://www.freshports.org/multimedia/ffmpeg/) is in progress to be updated to 6.0.
In order to build cmus [port](https://www.freshports.org/audio/cmus/) with it changes are needed:
```
https://github.com/FFmpeg/FFmpeg/commit/dd846bc4a9163f875cc2c4e99325c1a7b4ab8e7d
diff --git a/ip/ffmpeg.c b/ip/ffmpeg.c
index 09ed3fc..ea0b26f 100644
--- a/ip/ffmpeg.c
+++ b/ip/ffmpeg.c
@@ -202,9 +202,6 @@ static int ffmpeg_open(struct input_plugin_data *ip_data)
 			break;
 		}
 
-		if (codec->capabilities & AV_CODEC_CAP_TRUNCATED)
-			cc->flags |= AV_CODEC_FLAG_TRUNCATED;
-
 		if (avcodec_open2(cc, codec, NULL) < 0) {
 			d_print("could not open codec: %d, %s\n", cc->codec_id, avcodec_get_name(cc->codec_id));
 			err = -IP_ERROR_UNSUPPORTED_FILE_TYPE;
```

References:
https://git.alpinelinux.org/aports/tree/community/cmus/ffmpeg6.patch
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270179

Thanks

### PR DESCRIPTION
**Pull request by gavtroy**
Closes #1251

### CODE REVIEW

**Comment by brad0** [comment]
Or use

```
#if LIBAVCODEC_VERSION_INT < AV_VERSION_INT(59, 18, 100)
		if (codec->capabilities & AV_CODEC_CAP_TRUNCATED)
			cc->flags |= AV_CODEC_FLAG_TRUNCATED;
#endif
```

For compatibly with older than 6 and 6+.

**Comment by gavtroy** [comment]
Please correct me if you know more but I'd guess older versions are also fine with the flag not set. It's not clear why we were setting it or what it was supposed to do. It's not even clear if the flag was still relevant for the send_packet api. Of course it's not really explained anywhere so I don't know for sure.

**Comment by brad0** [comment]
https://git.videolan.org/?p=ffmpeg.git;a=commit;h=dd846bc4a9163f875cc2c4e99325c1a7b4ab8e7d

Looks like it might not have had any purpose with cmus being that it's an audio player and the flag only appears to have influenced (some) video codecs.

So this looks Ok as is after coming across that commit.

**Review by pgaskin — APPROVED** [review]
Tested. Works as expected, and fixes build on newer FFmpeg versions. `AV_CODEC_FLAG_TRUNCATED` does appear to only be used for videos.

https://copr.fedorainfracloud.org/coprs/pgaskin/cmus-testing/build/6153648/
https://github.com/pgaskin/cmus/commits/83309568a563a3e8f789c9bc3cef2b43b3a80101
https://nightly.link/pgaskin/rpms/actions/runs/5495006170

**Comment by pgaskin** [comment]
@flyingmutant

**Pull request merged**
