### PR TITLE
ip/cdio.c: only declare track_comments_found if HAVE_CDDB was defined

### PR DESCRIPTION
**Pull request by BouncyMaster**
Also change it's data type: int -> bool,

this variable is only needed when `HAVE_CDDB` is defined.

### CODE REVIEW

**Comment by nefthy** [comment]
Getting rid of track_comments_found does not have any real advantage, while the #ifdefs complicate the code. I'm not in favor of this PR.

**Comment by pgaskin** [comment]
Also, why char rather than bool?

**Comment by BouncyMaster** [comment]
> Getting rid of track_comments_found does not have any real advantage, while the #ifdefs complicate the code. I'm not in favor of this PR.

Well the reason for this PR is to get rid of the warning when building without cddb, plus I don't think it adds **that** much complexity.


> Also, why char rather than bool?

You're right, will update the PR with the change.

**Review by nefthy — APPROVED** [review]

**Comment by nefthy** [comment]
I think this can be merged.

**Review by pgaskin — APPROVED** [review]

**Pull request merged**
